name: deploy SSH
on:  [push]
jobs:

  buildDeploy:
    name: Build and deploy site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install NPM
        run: npm install

      - name: Install Gatsby
        run: npm install -g gatsby-cli@2.12.34

      - name: Install Gatsby Dependancies
        run: npm install gatsby-plugin-image gatsby-plugin-sharp gatsby-source-filesystem gatsby-source-graphql gatsby-plugin-mdx gatsby-transformer-sharp


      - name: Build
        run: gatsby build --prefix-paths

      - name: Verify
        run: ls -la public

      # - name: Copy File With SSH
      #   uses: appleboy/scp-action@v0.1.0
      
      #   with:
      #       host: ${{ secrets.IP }}
      #       username: ${{ secrets.USER }}
      #       key: ${{ secrets.PRIVATE_KEY }}
      #       port: ${{ secrets.PORT }}
      #       source: "./public"
      #       target: "/home/student06/site/html/"
      #       strip_components: 2

      # - name: Restart Docker
      #   uses: appleboy/ssh-action@v0.1.4
      #   with:
      #     host: ${{ secrets.IP }}
      #     username: ${{ secrets.USER }}
      #     key: ${{ secrets.PRIVATE_KEY }}
      #     port: ${{ secrets.PORT }}
      #     script: |
      #       docker restart student06

      - name: Delete temp directory and copy files
        uses: appleboy/ssh-action@v0.1.4
        with: 
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script:
            rm -rf /home/student06/site/root/*
            
      
      - name: Copy File with SSH
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "./publc"
          target: "home/student06/site/root"
          strip_components: 2

      - name: Move Files Atomically and Start Container
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script:
            rm -rf /home/student06/site/html/*
            mv /home/student06/site/root/* /home/student06/site/html
            if [ "$(docker inspect -f '{{.State.Running}}' student06 2>/dev/null)" != "true" ]; then
              docker start student06
            fi


